id: P404FDFB8
initial_creation_type: input
source_metadata:
  title: Tulku Zangpo Drakpa
  language: fr
  description: 'Texts revealed by the 14th-century tertön Zangpo Drakpa (bzang po
    grags pa):'
  volume:
    51d11f697bed4f238698ac3f308882d3:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    5885c0c1b00b45ea8f09e071a469c0fa:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    e0ffef26a79c4cc985210a409f6e21f4:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    5f46ea94834d4bd695fb3a0645928914:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    fde23dc5d6f44791936ec81833180983:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    a522f1aa30674047b4164630e5c6607f:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    dd1234e6f0e844edb61236a5b257c9ae:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    54feed37e2104416892d27bb829076a9:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
created_at: '2022-03-01T01:59:25.930501'
last_modified_at: '2022-03-01T01:59:25.930503'
